### ISSUE TITLE
dfp success or hints?

### ISSUE THREAD

**Issue by mateomtb** [krux/postscribe#10]
I was able to use this with old google dart tags and now can't seem to get this to work with dfp. Anyone had success or share how they did this? The tags and javascript get written out to the div but the javascript doesn't appear to actually fire. My latest attempt is like this.

So I have the basic setup in the header with slot declarations.

			<script type='text/javascript'>
			(function(){
			var useSSL = 'https:' == document.location.protocol;
			var src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
			document.write('<scr' + 'ipt src="' + src + '"></scr' + 'ipt>');
			})();
			</script>

			<script type="text/javascript">
			
			//Adslot 1 declaration
			var slot1= googletag.defineSlot('/8000/somesite.com/tags/news', [[300,250]],'cube1').setTargeting('pos',['Cube1_RRail_ATF']).addService(googletag.pubads());
			
			googletag.pubads().setTargeting('kv',['news']);
			googletag.pubads().enableSyncRendering();
			googletag.enableServices();
			
			</script>
			

Then my div on the page gets written into with the placement tag when my script is triggered.

<script type='text/javascript'>
var mcAdTag = '<scr'+'ipt type=\'text/javascript\'>googletag.display(\'cube1\');<\/scr' + 'ipt>';
 postscribe('#cube1', mcAdTag, {done: function() { loadTheAds(); }});
</script>

The markup and div targeted on the page..

			<div id='cube1'></div>

This results in no errors it just prints it out with no action.

	<div id='cube1'>
	<script type='text/javascript'>googletag.display('cube1');</script>
	</div>

**Comment by sethyates** [comment]
Closing this request due to inactivity.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
