### ISSUE TITLE
Conditional comments cause next character duplication

### ISSUE THREAD

**Issue by francoismassart** [krux/postscribe#102]
Hi there,
We are using postscribe to inject (dirty) JavaScript code from advertising partners and as often for advertising scripts, we do not have control on the injected code.

Some advertising campaigns use flash media and within the html markup they use conditional comments...

We noticed that using their markup with postscribe creates a bug as you can see in the image below.
![bug](https://cloud.githubusercontent.com/assets/704026/6368163/6f38cc18-bcda-11e4-85bd-5530552412f3.png)
After conducting different tests, I noticed that the first character following conditional comments was duplicated...

The BUG only happens when we use the "real" last version of the dist folder...
The files inside the dist folder (https://github.com/krux/postscribe/tree/master/dist) are out of date, as explained https://github.com/krux/postscribe/issues/99

Here is a quick demo
http://jsfiddle.net/9ga9sj2f/11/
The demo uses newer dist files generated from my fork of postscribe...
All I did is changing the version number from 1.3.2 to 1.3.3, compile and run the tests.

**Comment by francoismassart** [comment]
I added a test about this BUG on the branch bug-conditional-comments...
https://github.com/francoismassart/postscribe/tree/bug-conditional-comments

**Comment by francoismassart** [comment]
https://github.com/francoismassart/postscribe/commit/94c783b71bb608646c691f38472ac845581b8058 FIX the BUG... I'll create the pull request

**Comment by davidbarratt** [comment]
@francoismassart,

Has this been fixed in 1.4.0 ?

**Comment by screenman** [comment]
We have this issue in 1.4.0

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
