### ISSUE TITLE
Version of postscribe available via CDN is old [1.1.2]

### ISSUE THREAD

**Issue by kkshetty** [krux/postscribe#105]
Hey everyone,

The postscribe library turned out to be a godsend, when I recently had to implement a GPT passback tag for a client.

But I noticed that the latest version of postscribe.min.js available via CDN is an old one, namely 1.1.2

Link => http://cdnjs.com/libraries/postscribe

CDN link to postscribe => https://cdnjs.cloudflare.com/ajax/libs/postscribe/1.1.2/postscribe.min.js

I thought of giving the client a rawgit link => https://rawgit.com/.
But according to rawgit, 100% uptime is not guaranteed, since it is a free service

Just wanted to know when you next plan to update the postscribe version in the official CDNJS github repo => https://github.com/cdnjs/cdnjs

Thanks,
Krishna Kishore Shetty

**Comment by kkshetty** [comment]
I guess you guys are really busy. 

I will go ahead and create a pull request to submit the postscribe.min.js, and the package.json file myself to the CDNjs repo. Hope it gets merged.

**Comment by kkshetty** [comment]
I've gone ahead and created a pull request of my own.

https://github.com/cdnjs/cdnjs/pull/4444

Once it is approved, I will close this issue.

Thanks,
Krishna Kishore Shetty

**Comment by kkshetty** [comment]
Have gone ahead and submitted a pull request to the CDNjs repo

https://github.com/cdnjs/cdnjs/pull/4446

Once it is merged, I will close this issue

Thanks,
Krishna Kishore Shetty

**Comment by kkshetty** [comment]
Have submitted two pull requests to two different JavaScript CDN services.

https://github.com/cdnjs/cdnjs/pull/4448
and
https://github.com/jsdelivr/jsdelivr/pull/3883

**Comment by jimaek** [comment]
jsDelivr supports auto-updates as well https://github.com/jsdelivr/jsdelivr/#auto-updating

**Comment by kkshetty** [comment]
https://github.com/jsdelivr/jsdelivr/pull/3883 has been merged. Woohoo!

CDN Link => http://cdn.jsdelivr.net/postscribe/1.3.2/postscribe.min.js

Thanks,
Krishna Kishore Shetty

**Comment by kkshetty** [comment]
https://github.com/cdnjs/cdnjs/pull/4448 has also been merged.

CDN Link => https://cdnjs.cloudflare.com/ajax/libs/postscribe/1.3.2/postscribe.min.js

Thanks,
Krishna Kishore Shetty
