### ISSUE TITLE
Crashes: "TypeError: b is null"

### ISSUE THREAD

**Issue by fractalf** [krux/postscribe#108]
![postscribe-error](https://cloud.githubusercontent.com/assets/5707457/7229420/c748f870-e763-11e4-971e-977a89a725bb.jpg)

https://github.com/krux/postscribe/blob/master/postscribe.js#L534-L544

We async load all our ads through AdTech. Sometimes when "clicking to fast" every add stops loading due to the error shown in the image. It would be nice to throw in a test on *cursor* so that it doesn't crash the script and stops future loading

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
