### ISSUE TITLE
Multiple tests broken when not using htmlParser around the native document.write

### ISSUE THREAD

**Issue by gabrys** [krux/postscribe#110]
It's a follow up to the issue #33. The unit tests were added to prove postscribe works correctly with the following code:

```js
postscribe('#someelement', '<div id="first" style="background: red; padding: 5px">' +
  '<embed></embed>' +
  '<div id="second" style="background: yellow">Should be yellow in red box, right?</div>' +
'</div>');
```

When tested manually this is clearly broken. Use the postscribe tested I created to see why:

http://roy.lastlook.pl/~quake/postscribe-tester.html?code=%3Cdiv+id%3D%22first%22+style%3D%22background%3A+red%3B+padding%3A+5px%22%3E%0D%0A++%3Cembed%3E%3C%2Fembed%3E%0D%0A++%3Cdiv+id%3D%22second%22+style%3D%22background%3A+yellow%22%3EShould+be+yellow+in+red+box%2C+right%3F%3C%2Fdiv%3E%0D%0A%3C%2Fdiv%3E

I noticed that the expected.js has the wrong HTML (the one generated by postscribe in it), so the passed test doesn't prove anything. I noticed there's a ?generate_expected=1 URL param for the test.html, that I used and I found out it actually generates the same HTML as PostScribe does.

Then I started digging and I found out even for the native document.write htmlParser (with autoFix: true option) is run against the code to write, so it modified the HTML written by the browser.

I commented out the part (see #109) doing that and many more tests failed with ?generate_expected=1. I started checking the failed use cases manually, and yes they are HTML handled in a way that differs from how browser handles it. A simple example:

```html
<div><i></div>foo
```

http://roy.lastlook.pl/~quake/postscribe-tester.html?code=%3Cdiv%3E%3Ci%3E%3C%2Fdiv%3Efoo

**Comment by sethyates** [comment]
We believe this has been fixed in 2.0.0.  Please retest and raise a new issue according to the Contributing Guidelines if the issue persists.  Thanks.
