### ISSUE TITLE
Not injecting ads in IE

### ISSUE THREAD

**Issue by curlyfro** [krux/postscribe#116]
my company's website http://www.genengnews.com/ has advertising in the menu dropdowns.  

on mouseover i'm injecting ads like this:

    $("ul.channelbar > li").hover(
                function ()
                {
                    var adNumber = $(this).index() + 2;
                    var ord = window.ord || Math.floor(Math.random() * 1e16);
                    var adUrl = "http://ad.doubleclick.net/N308042/adj/Now_Bar/" + adNumber + ";sz=300x250;ord=" + ord;
                    var adContainer = $(this).find('div.nowbar_ad');

                    postscribe(adContainer, "<script src='" + adUrl + "'><\/script>");
                },
                function ()
                {
                    $('div.nowbar_ad').html('');
                }
            );

in IE *only* if you mouseover the menu elements really quickly, you loose the ad injection.  any ideas how to fix this?

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
