### ISSUE TITLE
Bug: postscribe add the "minor" character

### ISSUE THREAD

**Issue by lucalb** [krux/postscribe#125]
I use postscribe to show banner codes and in one case I found an error:
postscribe adds "<"  character and banner drops down

banner without postscribe: http://ad.payclick.it/extra/test2.html
banner with postscribe http://ad.payclick.it/extra/test/postscribe_test.html

refresh multiple times to display the banner

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
