### ISSUE TITLE
Problem with iframe contentWindow and Firefox

### ISSUE THREAD

**Issue by d3x7r0** [krux/postscribe#126]
I just received a complain from the firm that handles our advertising for us that some ads weren't loading on Firefox and, drilling down, I found that the issue lies with some new code they are using that uses the iframe.contentWindow to inject code into the page. This seems to work perfectly on Chrome but on Firefox 42.0b7 there's a quick flash of the iframe and then it's quickly deleted.

I've been trying to drill down into what's happening but can't seem to find the root of the problem.

A test case for the issue can be found on jsbin: http://jsbin.com/sogulel/edit?html,js,console,output

I would really appreciate any help tracking this one down.

**Comment by jeffallen6767** [comment]
Luis,

  I think the problem may be contentWindow instead of contentDocument ?

-jeff allen

**Comment by jeffallen6767** [comment]
LINK:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement

From: Jeff Allen <jallen@krux.com<mailto:jallen@krux.com>>
Date: Thursday, October 22, 2015 at 10:48 AM
To: krux/postscribe <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [postscribe] Problem with iframe contentWindow and Firefox (#126)

Luis,

  I think the problem may be contentWindow instead of contentDocument ?

-jeff allen

**Comment by d3x7r0** [comment]
Same issue: http://jsbin.com/rugewa/3/edit?html,js,console,output

You can clearly see that the document is properly written in both cases but latter the iframe is apparently reset. I'm really not sure if this is a postscribe or a Firefox issue but I'm finding it difficult to track down where in postscribe the change might be happening.

**Comment by jeffallen6767** [comment]
Please see if the information here:

http://stackoverflow.com/questions/9967478/iframe-content-disappears-on-firefox

And

http://stackoverflow.com/questions/7828502/cannot-set-document-body-innerhtml-of-iframe-in-firefox

Can help you?

-jeff

**Comment by jeffallen6767** [comment]
In plain words, I think we need to use:

1. Create new iframe element
2. Add (new iframe).onload event handler
3. Insert iframe element into document
4. Insert iframe content in onload event ( #2 )

This should allow iframe to complete loading BEFORE we add the content which should help the problem

-jeff

From: Jeff Allen <jallen@krux.com<mailto:jallen@krux.com>>
Date: Thursday, October 22, 2015 at 12:49 PM
To: krux/postscribe <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [postscribe] Problem with iframe contentWindow and Firefox (#126)

Please see if the information here:

http://stackoverflow.com/questions/9967478/iframe-content-disappears-on-firefox

And

http://stackoverflow.com/questions/7828502/cannot-set-document-body-innerhtml-of-iframe-in-firefox

Can help you?

-jeff

**Comment by d3x7r0** [comment]
Thank you very much for your help. I could have sworn I had tried to use the onload event before and it hadn't worked but maybe my lack of sleep betrayed me at the time. Your suggestion worked like a charm, now I just have to get them to actually use it.

I'll go ahead and close the issue now but the fixed code is in [this jsbin](http://jsbin.com/pufema/edit?html,js,console,output) for anyone that might have the same issue in the future.
