### ISSUE TITLE
postscribe multiple request crashes in react routing

### ISSUE THREAD

**Issue by JianGuo222** [krux/postscribe#129]
hi,

I found this frustrating issue when using postscribe multiple times on the same page in different react component after mounted. 

I have postscribe(null, '', 'clear') in the initialized function, but it didn't fixed the crashing issue when I go to another page and come back many times.

is anybody experiencing the same issue?

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
