### ISSUE TITLE
README.md dead link

### ISSUE THREAD

**Issue by KIPdeKIP** [krux/postscribe#130]
https://github.com/krux/postscribe/#faq

The url on "Wat?" should be changed to: `https://web.archive.org/web/20130607092418/http://izit.org/sites/izit.org/files/1329697955565.jpg`, another location or removed.

\<sarcasm>This is truly the worst issue and makes PostScribe impossible to work with.\</sarcasm>

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
