### ISSUE TITLE
onerror and onload on script tags not firing

### ISSUE THREAD

**Issue by EnricoKestenholz** [krux/postscribe#132]
Hi,
on line [postscribe.js line 568]( https://github.com/krux/postscribe/blob/master/postscribe.js#L568)  overwrites scripts onload and onerror events.

I've found this to be a problem when doubleclick load some banners with this code

    function mraidDone(){
         /*actual banner*/
    }
    document.write('\x3cscript type="text/javascript" src="mraid.js" onload="mraidDone()" onerror="mraidDone()"\x3e\x3c/script\x3e');

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
