### ISSUE TITLE
Is htmlParser.js needed?

### ISSUE THREAD

**Issue by KenSharp** [krux/postscribe#136]
I apologise for asking a question in a bug tracker but Github is yet to provide a question/answer section...

Is htmlParser.js needed?

I messed up my code which meant that it didn't load, but postscribe worked anyway. Is it simply the case that I'm missing some functions that I've not yet used?

I've fixed the code but I don't know if I'm needlessly loading another script now.

Thanks and sorry again for asking this way.

**Comment by jnewman** [comment]
If you're using postscribe form the dist folder, then htmlParser is included already.
