### ISSUE TITLE
Missing file as src for script tag causes uncaught exception

### ISSUE THREAD

**Issue by ekilah** [krux/postscribe#137]
Hi,

I don't use your library, but I work with a client that does, and we just spent a lot of time debugging an issue with his ad.

[This line](https://github.com/krux/postscribe/blob/228335ecd08ac0a95065e4d0148cb3ec0bdbc732/postscribe.js#L32) in the `OPTIONS` object of `postscribe.js` defaults to throwing an uncaught exception if write causes an exception.

This caused issues for us because we were loading the ad on an iOS device, and the Safari web inspector does not have a way to see this exception that's thrown immediately (separate issue - the web inspector can't be opened immediately programmatically).

The problematic line in my client's js was

```
<script src="not_going_to_exist.js"></script>
```

This missing file caused the js on the page to stop executing, which wasn't what we expected (and probably isn't helpful to many people - console logging this would be much preferred in my opinion). This is certainly not what browsers do when they encounter a missing file on their own w/o this library.

Is this the desired default behavior? Maybe there's something better that can be done here to prevent the pain I went through :tongue: but maybe not. Just wanted to point this out as a potential pain point (it was for me).

**Comment by sethyates** [comment]
@ekilah this is by design and there is provision for the library user to specify an error handler in the options to the `postscribe` function.  Changing how it is now would be a breaking change.

**Comment by ekilah** [comment]
I can see how that would be an issue also. Maybe the default case can have a console log as well or something? This wouldn't have helped me since the Safari web inspector for iOS devices is lame, but it could help others. Up to you all - like I said I don't currently use the library!

**Comment by sethyates** [comment]
@ekilah thanks for the feedback!  we'll look into adding a `console.error` or something like that.
