### ISSUE TITLE
Chrome producing Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by sajalaspl** [krux/postscribe#159]
I would appreciate your input on this.

![chrome](https://cloud.githubusercontent.com/assets/3337683/14672181/c8370ac6-0713-11e6-9d5d-6ac5008c36f0.png)

**Comment by sethyates** [comment]
As per the [Issue Guidelines](https://github.com/krux/postscribe#issue-guidelines), could you please provide a link to a jsfiddle or link to a publicly accessible URL that reproduces the problem?

**Comment by sajalaspl** [comment]
http://karjalainen.fi (Please test with google chrome, and it'll be produced randomly).

**Comment by jnewman** [comment]
Fixed in https://github.com/krux/prescribe/pull/22 will require a new release of postscribe w/ the new version.

**Comment by sethyates** [comment]
Fixed in 2.0.3.  Please upgrade your script from 1.4.0.

**Comment by sajalaspl** [comment]
Hi Sethyates,

First of all thanks for the quick action.

Although, I'm having difficult time finding the latest 2.0.3 version source files. I looked at here https://github.com/krux/postscribe/tree/master/src, but I'm not sure how to use it with my website. Earlier, I was simply using it following way.

<div id="ad1">Ad-1</div>
<script src="/postscribe/htmlParser.js" type="text/javascript"></script>
<script src="/postscribe/postscribe.js" type="text/javascript"></script>

<script type="text/javascript">
  jQuery(document).ready(function() {
    if ( jQuery( "#ad1" ).length ) {
      postscribe('#ad1', '<script src="http://eas3.emediate.se/eas?cu=8272;cre=mu;js=y;pageviewid=;target=_blank" type="text/javascript"><\/script>');
    }
});
</script>

Also, the cloud link is not working too, https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.0/postscribe.min.js.

**Comment by jnewman** [comment]
Created #160 to track the cliff flare link

**Comment by sajalaspl** [comment]
Hi Jnewman,

Thanks for creating new issue to fix the link. But, do you think is it still possible to use Postscribe in old way, by including htmlParser and Postscribe js files and just calling the postscribe function?

I would really appreciate your feedback on this. Thanks in advance.

**Comment by jnewman** [comment]
When #167 is fixed you can include just the postscribe.js available at that URL. We're swallowing the parser instead of leaving it as a separate module. Alternately, you can install npm and get the built file from the node_modules folder after you follow these instructions: https://github.com/krux/postscribe#npm

**Comment by jnewman** [comment]
Filed #168 that would make this a bit simpler if you don't want to use npm, bower, or cloudflare

**Comment by sajalaspl** [comment]
Many Thanks @jnewman, I used the file from npm built "./dist/postscribe.js". Unfortunately, that produced another issue, #172.
