### ISSUE TITLE
Fix cloud flare link

### ISSUE THREAD

**Issue by jnewman** [krux/postscribe#167]
Used to support distribution via cloud flare

**Comment by jnewman** [comment]
Added PR here: https://github.com/cdnjs/cdnjs/pull/7709

**Comment by jguerine** [comment]
Is there a way to now get the full library without installing it?
Thanks !

**Comment by jnewman** [comment]
Fixed by https://github.com/cdnjs/cdnjs/pull/7709

You can download the latest from the cdn
