### ISSUE TITLE
Browser link is not working

### ISSUE THREAD

**Issue by jguerine** [krux/postscribe#178]
From : https://github.com/krux/postscribe

If you just want to use the script without installing anything, use the following to load the script from cdnjs:
<script src="https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.0/postscribe.min.js"></script>

https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.0/postscribe.min.js
>>> 404.

Best

**Comment by sethyates** [comment]
Duplicate of #167
