### ISSUE TITLE
«&» are escaped as «&amp;» resulting in bad calls

### ISSUE THREAD

**Issue by dugwood** [krux/postscribe#206]
I was trying to asynchronously load SmartAdServer requests, but the urls are rewritten:
https://jsfiddle.net/x1m6mvv6/5/

Request URL:https://ww62.smartadserver.com/ac?nwid=0&amp;siteid=2301&amp;pgid=378531&amp;fmtid=438&amp;visit=m&amp;tmstp=5021521458&amp;orgfmtid=438&amp;tag=sas_438&amp;pgDomain=https://fiddle.jshell.net

=> should not have «&amp;»

I know that SmartAdServer provides an asynchronous mode, but I have some passbacks that won't work after the main call.

Maybe related to: https://github.com/krux/postscribe/issues/98

Thanks.

**Comment by sethyates** [comment]
Hi @dugwood,

I've looked into this more.  The escaping actually appears to be coming from SAS themselves.  I modified your fiddle as follows:

1. replaced the postscribe call with an inline call `sas.call("std", { siteId: 2301, pageId: 378531, formatId:  438, target: ''});`
1. clicked on https://ww62.smartadserver.com/config.js?nwid=62 which redirected to https://ww62.smartadserver.com/diff/js/smart.js.
1. copies the contents of that file
1. pasted the contents of that file at the top of the JavaScript pane
1. removed the external resources
1. added the following code at the top of the JavaScript pane: `document.write = console.debug;`
1. clicked Run and checked the Developer Tools console and observed:

```
<script id="sas_script1" type="text/javascript" src="https://ww62.smartadserver.com/ac?nwid=0&amp;siteid=2301&amp;pgid=378531&am…43&amp;orgfmtid=438&amp;tag=sas_438&amp;pgDomain=https://fiddle.jshell.net"></script>
```

**Comment by dugwood** [comment]
I think I won't have to use it anymore, but so far this document.write seems good to me: & should be escaped as &amp; in url that are part of an attribute. But if there's a call (img.src or ajax call), those &amp; should be dealt as &.

Thanks for your time and great script anyway.
