### ISSUE TITLE
Problems using bower package

### ISSUE THREAD

**Issue by justinshea** [krux/postscribe#260]
Hi,

The build is failing for me. Steps followed:
npm install
npm run build

Error message attached.

I installed the package via bower. My expectation with bower is that the package is already built.

Not sure if the build fail is due to a local env factor. I will keep plugging away at it from my end. I hope you find this information useful and if you have any insight please share...

Thx
Justin

![postscribe-build-fail](https://cloud.githubusercontent.com/assets/3589511/16968552/959cf736-4ddd-11e6-9386-358b5c87b44d.png)

**Comment by sethyates** [comment]
The key there is "Failed to load external module `babel*register`.  Looks like you don't have all of the modules installed correctly.  Perhaps delete the `node_modules` directory and reinstall.

**Comment by sethyates** [comment]
Also `I installed the package via bower.` - I don't think this installs a package.json with all of the dependencies.

**Comment by justinshea** [comment]
I am really struggling here. 

- I've made sure the package.json is most recent version 
- I deleted the entire node_modules directory and ran 'npm cache clean'
- I did a fresh 'npm install'

I don't know what else I should be doing.

The error message I receive now is slightly different:
![postscribe-build-error2](https://cloud.githubusercontent.com/assets/3589511/16970825/b1cb28a6-4dec-11e6-9962-696aea0a1e7a.png)

**Comment by sethyates** [comment]
In the interim, could you just download the version from the CDN? `https://cdnjs.cloudflare.com/ajax/libs/postscribe/2.0.6/postscribe.min.js`?  I'll see what can be done about fixing up the `bower.json` file.

**Comment by justinshea** [comment]
thanks...

I would request shipping with the most recent build via bower. 
I am sure this has something to do with my local environment but including built version could help hacks like me avoid all of this misery :)

**Comment by sethyates** [comment]
Another option would be to switch to `npm` and put the `postscribe` dependency in your main `package.json` rather than using bower.  The version in npm registry is pre-built.

**Comment by justinshea** [comment]
thanks

**Comment by justinshea** [comment]
Hi - I had to bring in my project to a new machine today and so I gave the postscribe build process another shot....It worked! I used the same steps from yesterday:

- bower install (postscribe is a front-end dependency listed in bower.json for project)
- cd into the postscribe project
- npm install to install all postscribe build dependencies
- npm run buil

Now, I am trying to figure out why this wasn't working in my other environment. The only thing that comes to mind is that I do not have gulp installed globally in the other environment...

**Comment by justinshea** [comment]
When I attempted to build postscribe from the npm package I got the same error..so it would seem this is definitely a local environment thing.

Problem was finally solved:
"npm install --save-dev gulp-util"

Weird that I still had to do this after clearing cache, fresh installs etc..

Thanks for your feedback...
