### ISSUE TITLE
onerror and onload on script tags not firing

### ISSUE THREAD

**Issue by zaffudo** [krux/postscribe#262]
The issue described in https://github.com/krux/postscribe/issues/132 does not appear to be fixed in version 2.0.6. onload and onerrorevents do not appear to be firing on scripts written via Postscribe.

The simple test case found below fails to execute the documentDone function:
https://github.com/krux/postscribe/pull/133/commits/df34363fabfdc3fa3124dc78fdc373a82dea6148

**Comment by sethyates** [comment]
@zaffudo I have some changes here https://github.com/krux/postscribe/pull/312 which fix this in unit test.  could you check that branch out and let me know if it works for you?
