### ISSUE TITLE
document.write call fails when there's a space in the value of a script tag attribute

### ISSUE THREAD

**Issue by d3x7r0** [krux/postscribe#345]
We found an issue when writing a script tag with a filename that contains space characters.

Example:
```javascript
<script src=https://secure-ds.serving-sys.com/BurstingRes//CustomScripts/OK - PL_ResponsivePushdown_CFV001.js></script>
```

The rendering then fails when it attempts to add the attribute '-' to the element.

**Comment by sethyates** [comment]
WONT FIX.  As per the HTML4 RFC, that is invalid HTML anyway: https://www.w3.org/TR/html4/interact/scripts.html#h-18.2.1.  The attribute must be enclosed in quotes.

**Comment by d3x7r0** [comment]
Sorry about that. I actually only noticed the lack of quotes after posting the issue. We'll report this to the advertiser.
