### ISSUE TITLE
Does this work with Polymer?

### ISSUE THREAD

**Issue by bhat-man** [krux/postscribe#434]
I cannot figure out how to get this to work with Polymer so that it will load an ad.  I have a standard polymer template in which I am trying to load an ad.  If anyone could provide an example of this working inside of a Polymer template that would be cool.

**Comment by jnewman** [comment]
I'm not generally looking to build a plugin for frameworks; this is plain JS, so you should be able to plugin into whatever system Polymer has pretty easily unless they hide a lot of globals.
