### ISSUE TITLE
External Scripts, with and without document.write statements, and a Cancelled Callback

### ISSUE THREAD

**Issue by tomgallagher** [krux/postscribe#452]
Hi

Thanks for the awesome library, really useful.

I'm trying to use PostScribe to manage script injection with external scripts, some of which may have document.write calls in them, some of which may not. At the moment I'm sending all of them through Postscribe because even if there's no document.write statement it's very important to maintain the order of the external scripts.

The problem I'm having is that when I send an external script without a document.write statement in it to Postscribe, I get back a cancel object and then Postscribe ceases to function, as you might expect.

In order to work out whether there's a document.write statement in the script, I would have to find some way of downloading and searching the cross-domain scripts with some sort of regex, I guess. It seems like you're already doing something better. 

What would be even better from my point of view would be a `cancelled ` callback, which I can then work with and Postscribe would continue to perform its function for those external scripts that do have document write statements.

Tom

**Comment by tomgallagher** [comment]
OK this may not be the use case, but if you add in this callback:

beforeWriteToken: a callback called before writing a token

and do nothing except log a message to the console, then the done function will fire even if there are no document.write statements in the external script.  

Worth knowing maybe for someone.

**Comment by jnewman** [comment]
Does the error callback not work for this? https://github.com/krux/postscribe/blob/master/src/postscribe.js#L65

**Comment by tomgallagher** [comment]
Nope doesn't get fired

**Comment by jnewman** [comment]
Are you running that on an HTTPS page? IF you give me an webpage I can test on then I'll take a look

**Comment by tomgallagher** [comment]
Not https no. I'm just injecting Postscribe at the moment into this page:

http://www.noobmeter.com/compareplayers/eu/all/tomg1/gallam1

And then testing the code in the console.

**Comment by tomgallagher** [comment]
As I said in the other thread, I'm running through a set of external scripts in an array, then adding each of those scripts in turn. I've just tested that page with an injection and then running in the console and it works fine. Could there be some issue with adding multiple Postscribe tags in quick succession, i.e. before the previous one has finished? It did all work when I was running them with the releaseAsync: true in the options object and adding async="async" to the script tags. Shall I post some code from my project?

**Comment by tomgallagher** [comment]
```
var frag = document.createDocumentFragment();
console.log(source.substring(0, 50) + " (50 chars) now working via POSTSCRIBE with Unique ID of: " + arrayEntry[3]);
var postscribeScript = document.createElement('script');
if (arrayEntry[5]) { postscribeScript.type = arrayEntry[5]; } else { postscribeScript.type = 'text/javascript'; }
postscribeScript.charset = 'utf-8';
postscribeScript.async = false;
            
postscribeScript.textContent = "postscribe(\'#" + arrayEntry[3] + "\', \'<script src=" + source + "><\/script>\', { done: function() { console.info(\'Turbo Postscribe External Script (50 chars) " + source.substring(0, 50) + " has been Processed.\'); var marker = document.createElement(\'div\'); marker.setAttribute(\'data-turbo-script-type\', \'" + arrayEntry[0] + "\'); marker.setAttribute(\'data-turbo-script-content\', \'" + source.substring(0, 50) + "\'); marker.setAttribute(\'data-turbo-script-delivered\', \'" + arrayEntry[4] + "\'); (document.body||document.documentElement).appendChild(marker); }, error: function() { console.error(\'Turbo Postscribe External Script (50 chars) " + source.substring(0, 50) + " has hit an error. Starting Error Handler\'); var marker = document.createElement(\'div\'); marker.setAttribute(\'data-turbo-script-type\', '" + arrayEntry[0] + "\'); marker.setAttribute(\'data-turbo-script-content\', \'" + source.substring(0, 50) + "\'); marker.setAttribute(\'data-turbo-script-error-marker\', \'" + arrayEntry[4] + "\'); (document.body||document.documentElement).appendChild(marker); } });"
postscribeScript.setAttribute('data-optimised-script', 'true');
frag.appendChild(postscribeScript);
targetNode.appendChild(frag);
```

**Comment by jnewman** [comment]
Can you setup a webpage to debug this with?

**Comment by tomgallagher** [comment]
Just sent you an email.

**Comment by tomgallagher** [comment]
Hi 

OK so this was a timing issue. I was removing the first param targetnode from the page, after Postscribe checks for its presence but before the script was actually written to the page. So Postscribe just failed silently. Maybe another check for the target node before writing to the page? And maybe I'll leave tidying up until the whole thing is actually working. Anyway, thanks for your time @jnewman 

Tom

**Comment by jnewman** [comment]
I'll add a check in a future release
