### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by tomgallagher** [krux/postscribe#454]
Hi, me again

This inline script code string is causing an invalid or unexpected token error :

`"/*<![CDATA[*/ (function(){ if (typeof orb !== 'undefined' && typeof orb.fig === 'function') { if (orb.fig('ad') && orb.fig('uk') == 0) { bbcdotcom.data = { ads: (orb.fig('ad') ? 1 : 0), stats: (orb.fig('uk') == 0 ? 1 : 0), statsProvider: orb.fig('ap') }; } } else { document.write('<script type=\"text/javascript\" src=\"'+('https:' == document.location.protocol ? 'https://www.bbc.com' : 'http://tps.bbc.com')+'/wwscripts/data\"></script>'); } })(); /*]]>*/"`

Any ideas?

Tom

**Comment by tomgallagher** [comment]
Tested this on a few other scripts and it looks like it could be the shorthand conditional in the document.write string that's causing the problem.

**Comment by tomgallagher** [comment]
Using Postscribe.max.js, the above script once returned by tok.content in WriteStream.prototype._buildScript is as follows:

`/*<![CDATA[*/ (function(){ if (typeof orb !== 'undefined' && typeof orb.fig === 'function') { if (orb.fig('ad') && orb.fig('uk') == 0) { bbcdotcom.data = { ads: (orb.fig('ad') ? 1 : 0), stats: (orb.fig('uk') == 0 ? 1 : 0), statsProvider: orb.fig('ap') }; } } else { document.write('<script type="text/javascript" src="'+('https:' == document.location.protocol ? 'https://www.bbc.com' : 'http://tps.bbc.com')+'/wwscripts/data">`

So this part is missing from the end and that's how it gets written to the DOM.

`</script>'); } })(); /*]]>*/`

Don't know if that helps.

**Comment by tomgallagher** [comment]
So the problem lies in the conditional placed in the src at this line:

`src="'+('https:' == document.location.protocol ? 'https://www.bbc.com' : 'http://tps.bbc.com')+'/wwscripts/data"`

Postscribe.max.js around line 690, in WriteStream.prototype._handleScriptToken, has, after this line:

`tok.src = tok.attrs.src || tok.attrs.SRC;`

tok.src as undefined. So somehow the conditional src needs to be processed.

**Comment by gauravsafetynet** [comment]
inline script code gives unexpected token error
