### ISSUE TITLE
Very very slow render times

### ISSUE THREAD

**Issue by amontpetit** [krux/postscribe#472]
Embedding a Formstack form using Postscribe, I end up with 1min+ load times. Page sits there empty then loads the form as normal, but there's a solid minute. The form is rather large, but embedding the form directly loads instantaneously.

**Comment by keithslater** [comment]
Did you find a solution to this? I'm running into the same thing.

**Comment by amontpetit** [comment]
> Did you find a solution to this? I'm running into the same thing.

We've abandoned that solution and are working on doing things ourselves. We never did come up with a solution, but the epic this issue was related to was temporarily shelved.
