### ISSUE TITLE
Script inside a div

### ISSUE THREAD

**Issue by hirohanin** [krux/postscribe#474]
Hi

Can you tell if postscriibe can support delivery of adtag which has script inside a div 

E.g

A tag which works is  <script src"blah"> </script>

But if the ad tag is 
<div id="myid"> <script src"blah"> </script> </div>

Regards
hirohanin

**Comment by hirohanin** [comment]
@jnewman any feedback

**Comment by jnewman** [comment]
I don't see a reason it wouldn't.

**Comment by hirohanin** [comment]
&lt;div&gt;<script src"blah"> </script>&lt;/div&gt;

**Comment by hirohanin** [comment]
The divs went missing the above is the one

**Comment by jnewman** [comment]
@hirohanin can you give me a test page on e.g., https://plnkr.co/edit/
