### ISSUE TITLE
DFP 6 broken in use with PostScribe

### ISSUE THREAD

**Issue by AndyOGo** [krux/postscribe#54]
I just had to set up a campaign from GoldBach and faced various Issues in combination with PostScribe.

Firstly DFP supports two modes - synchronous and asynchronous Ad Loading:
Synchronous
---
This mode will throw a 404 HTTP Error trying to load gpt_impl_35.js.
"NetworkError: 404 Not Found - http://www.qa1-tutti.dev/http&#58;&#47;&#47;partner&#46;googleadservices&#46;com&#47;gpt&#47;pubads&#95;impl&#95;35&#46;js"
The reason for this is that DFP in sync mode correctly escapes HTML Entities for document.write. But Since we are using PostScribe here, this brakes the above URL.
Solution add an unescapeHTMLEntities function to HTMLParser.
Asynchronous
---
This mode does not suffer from the HTML Entities Issue but instead is not working in IE8 and below.
According to this StackOverflow post, the reason for this is the on site extension of Host Objects in combination with DFP JS using for in to loop over Array elements:
http://stackoverflow.com/questions/8751620/google-ads-not-showing-up-in-ie8
I removed all our EcmaScript 5 Pollyfills but still it was not working in IE8...

---
Unfortunately after HTML Entities fix, it still breaks in firefox - I only got async DFP working here. in lte IE8 sync work with that fix.

**Comment by sethyates** [comment]
Closing this request due to inactivity.  Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
