### ISSUE TITLE
postscribe problem with nested  ul  tags

### ISSUE THREAD

**Issue by delphiajones** [krux/postscribe#80]
ul tags are not properly nested using postscribe.js 1.3.2
`postscribe("#info2"`
`			, "<ul>"`
`			+ "<li>1 - one"`
`			+ "<li>2 - two"`
`			+ 	"<ul><li>a - aaya<li>b - bee</ul>"`
`			+ "<li>3 - three"`
`			+ "</ul>"`
`		);`

RESULT:
`<ul><li>`1 - one`<li>`2 - two`</ul>` 
`<ul><li>`a - aaya`<li>`b - bee`</ul>`
`<li>`3 - three

**Comment by sethyates** [comment]
Moved to https://github.com/krux/prescribe/issues/7
