### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null 

### ISSUE THREAD

**Issue by haapti** [krux/postscribe#83]
My page load all content with AJAX. In some point postscribe stop working and give me these errors

Uncaught TypeError: Cannot read property 'parentNode' of null
Uncaught #<Object> 

Have any idea what would be the cause of these errors?

I can give an access to the page for a look. It's hard to give more details via this post.

**Comment by bnkuhn** [comment]
Can you go into more detail about what you mean by "hanging" event listeners?  I could probably interpret that in a few ways.

I'm seeing the same error message coming from this line:
https://github.com/krux/postscribe/blob/master/dist/postscribe.js#L902

**Comment by jnewman** [comment]
The issue in the other users app was that he wasn't removing event listeners when removing DOM nodes. In the event listeners he was calling write from postscribe, but the write was targeted at a removed Node, which throws a null pointers. If you have jsfiddle or similar that reproduces I'm happy to take a look.

**Comment by van-nguyen** [comment]
+1, is there a way to do a try catch block to stop everything in that postscribe call when we transition in a SPA?
