### ISSUE TITLE
In the head!

### ISSUE THREAD

**Issue by KolyaKorruptis** [krux/postscribe#94]
Can postscribe deal with document.write in the page head? Could you please give an example?

I have a document.write command here that writes a script tag into the head, right where it is called. How am I to provide an ID inside the page head? 

Also the loaded script calls further document.write's. Will postscribe be able to catch those as well?

**Comment by jnewman** [comment]
It should _just work_ set an ID on the element getElementById doesn't mind where in the dom an element is.

**Comment by KolyaKorruptis** [comment]
The point is that you cannot use a DIV or SPAN with an ID inside the head, as in your examples. 
And since I don't know what proscribe does with that element I don't know if I can use a SCRIPT tag + ID instead.
For the same reason  I'm wondering if I can use the same element ID in multiple proscribe calls.

**Comment by KolyaKorruptis** [comment]
Using a SCRIPT tag with an ID does not work for me. 

Could you please give an example how to use proscribe in the document head?

**Comment by jnewman** [comment]
If you just want to append then you can do:
```js
postscribe(document.head, '<script>alert("hello")<\/script>');
```
It's also possible to put flow elements in the head, but if you'd rather not, then appending works fine.

**Comment by KolyaKorruptis** [comment]
Thank you, this works very well for me.
