### ISSUE TITLE
SRC attribute shouldn't be unescaped

### ISSUE THREAD

**Issue by benjaminclot** [krux/postscribe#98]
SRC attribute, either for scripts, images, etc. doesn't have to be escaped. With ads calling ads calling ads and so on today, I had cases where unescaping entities messed up with sources ("&" being often the main culprit). Thus, I think that we should leave this attribute "as is".

See PR #97.

**Comment by thiagonzalez** [comment]
I had the same situation. My JS calls an URL with '&amp;param=' and postscribe converts it to '¶m='
Did your PR fixed it @benjaminclot ? Your problem is the same that what I told here?

**Comment by benjaminclot** [comment]
Yes @thiagonzalez, I don't have problems with ampersands anymore.

**Comment by thiagonzalez** [comment]
Thank you @benjaminclot ! It works like a charm :100:

**Comment by sethyates** [comment]
We believe this is fixed in 2.0.0. Please retest against 2.0.0 release and open a new issue following Issue Reporting guidelines in 2.0.0 if you believe this is still an issue.
