### ISSUE TITLE
postscribe.js 1.3.2 on github isn't uptodate

### ISSUE THREAD

**Issue by messenjer** [krux/postscribe#99]
Hello, 

We use the latest stable version of postscribe (1.3.2) since june 2014.

For few months, our advertising studio report to us a problem with Google Chrome Browser and postscribe.

Today, by chance I saw that there is in the master branch an uptodate version of postscribe.

* https://github.com/krux/postscribe/tree/master/dist 

With 2 bugfixes : 
* https://github.com/krux/postscribe/issues/79
* https://github.com/krux/postscribe/issues/81 

Now, I'm using the version from the master branch on our production server.

It's possible to put here https://github.com/krux/postscribe/releases a version 1.3.2 ( --> 1.3.3) with these bugfixes.

Thanks a lot for postscribe and your work on async ads, he helps us a lot for our webperf tracks.

Regards

Mathieu

**Comment by jnewman** [comment]
Yeah, I'm a bit behind on releasing. I'll do a release today or tomorrow w/ the bug fixes.

FYI you can point at a commit instead of master, which is a lot more stable. We won't rebase master so you're gonna have a stable version. In npm for example you'd put:
```json
{
  "devDependencies": {
    "postscribe": "https://github.com/krux/postscribe/tarball/f38a1c44d9de23cf1310b9adc94cdec0ff07b2ba"
  }
}
```

**Comment by messenjer** [comment]
Thanks.

Last week, I did a clone of the master, and did a build, uglify to use it.

Regards

Mathieu
